#!/bin/sh

# replace each FOO=bar argument with -e 's/.*FOO.*/FOO=bar/', then sed "$@"
set_build_opts() {
    for v; do
        set -- "$@" -e "s/.*${v%%=*}.*/$v/"
        shift
    done
    sed "$@"
}

set_unicode_opts() {  # keep in sync with scripts/mk_mingw64u_defconfig
    set_build_opts \
        CONFIG_FEATURE_UTF8_MANIFEST=y \
        CONFIG_FEATURE_UTF8_INPUT=y \
        CONFIG_FEATURE_UTF8_OUTPUT=y \
        CONFIG_UNICODE_SUPPORT=y \
        CONFIG_FEATURE_CHECK_UNICODE_IN_ENV=y \
        CONFIG_SUBST_WCHAR=63 \
        CONFIG_LAST_SUPPORTED_WCHAR=1114111 \
        CONFIG_UNICODE_COMBINING_WCHARS=y \
        CONFIG_UNICODE_WIDE_WCHARS=y
}

set -eux

cd -- "$(dirname "$0")"

N=$(nproc)

sed s/x86_64-w64-mingw32-// < configs/mingw64_defconfig \
| ([ "${1-}" = -u ] && set_unicode_opts || cat) \
> configs/avih_defconfig

time make avih_defconfig -j$N
time make -j$((1 + N*2/3))  # don't consume all cores...
