#!/bin/sh

: ${UTF8_MODE=MANIFEST}  # MANIFEST or NATIVE when using -u

# replace each FOO=bar argument with -e 's/.*FOO.*/FOO=bar/', then sed "$@"
set_build_opts() {
    for v; do
        case $v in
        -*) set -- "$@" -e "s/.*${v#-}.*/# ${v#-} is not set/";;
         *) set -- "$@" -e "s/.*${v%%=*}.*/$v/";;
        esac
        shift
    done
    sed "$@"
}

set_unicode_opts() {  # keep in sync with scripts/mk_mingw64u_defconfig
    [ "${UTF8_MODE}" = NATIVE ] || set -- "$@" -CONFIG_FEATURE_APP_MANIFEST
    set_build_opts "$@" \
        -CONFIG_FEATURE_TOOLCHAIN_MANIFEST \
        CONFIG_FEATURE_UTF8_${UTF8_MODE}=y \
        CONFIG_FEATURE_UTF8_INPUT=y \
        CONFIG_FEATURE_UTF8_OUTPUT=y \
        CONFIG_UNICODE_SUPPORT=y \
        CONFIG_FEATURE_CHECK_UNICODE_IN_ENV=y \
        CONFIG_SUBST_WCHAR=63 \
        CONFIG_LAST_SUPPORTED_WCHAR=1114111 \
        CONFIG_UNICODE_COMBINING_WCHARS=y \
        CONFIG_UNICODE_WIDE_WCHARS=y
}

set -eux

cd -- "$(dirname "$0")"

N=$(nproc)

strstr() { ! case $1 in *"$2"*) false; esac; }

sed s/x86_64-w64-mingw32-// < configs/mingw64_defconfig \
| ([ "${1-}" = -u ] && set_unicode_opts || cat) \
| (strstr "$*" clang && set_build_opts -CONFIG_STATIC_LIBGCC || cat) \
> configs/avih_defconfig

[ "${1-}" != -u ] || shift
time make avih_defconfig -j$N "$@"
time make -j$((1 + N*2/3)) "$@"  # don't consume all cores...
